### ISSUE TITLE
New LDS layers not picked up

### ISSUE THREAD

**Issue by SPlanzer** [linz/nzgoal_audit_script#10]
Hi Simon,
 
I’m running the Q4 NZ GOAL report and found few new LDS layers are not in the report. It also looks like the script truncates the LDS layer id to only 5 digits. I attached the result here and please see the ‘NO CORRESPONDING LDS ID IN FORMS SPREAD SHEET’ section.
 
Here is the link to the script in Github: https://github.com/linz/nzgoal_audit_script
 
Any ideas?
 
Thank you,
Sisi

**Comment by SPlanzer** [comment]
Hi @SsiZhang can you send me some of the ids that are not being picked up?

I will look at this this morning

**Comment by SsiZhang** [comment]
101292-nz-building-outlines-all-sources
102477-manawatu-whanganui-lidar-1m-index-tiles-2015
102475-manawatu-whanganui-lidar-1m-dem-2015
102476-manawatu-whanganui-lidar-1m-dsm-2015

@SPlanzer here are few examples. Thank you.

**Comment by SPlanzer** [comment]
resolved by https://github.com/linz/nzgoal_audit_script/commit/bb7b64110d895fb2b2571068fa605a172b0e3053
