### ISSUE TITLE
Layer vs table identifiers

### ISSUE THREAD

**Issue by billgeo** [linz/nzgoal_audit_script#4]
Can you double check that layer and table identifiers are unique? Like can you have ../table/1234 and ../layer/1234? And will that cause a problem with your python script?

**Comment by SPlanzer** [comment]
Good point. 

I have ran a quick check on the IDs and can confirm as they stand now via the RSS feed these are all unique

[quick script to evaluate uniqueness](https://gist.github.com/SPlanzer/eaa92e5142f51a196f54893e564dca3f)

**Comment by billgeo** [comment]
Thanks.
